LOSS: "mse"
DATASET_PATH: '../dataset'
CONTEXTQ_FILE: '../dataset/contexts/anthropic_claude_context.csv'

TRAIN_FILE: '../dataset/train_set.txt'
DEV_FILE: '../dataset/val_set.txt'
TEST_FILE: '../dataset/test_set.txt'

FRAME THRESHOLD: 0.1
PROJECT NAME: "baseline"
BATCH_SIZE: 32
LR: 0.00001
MAX_EPOCHS: 10000
MAX_PATIENCE: 20
HIDDEN_SIZE: 256
DROPOUT: 0.15
NUM_LAYERS: 4
LINEAR_LAYERS: [256]
RNN_TYPE: 'GRU' #GRU or LSTM
OUT_SIZE: 1
ACTIVATION: 'sigmoid'
ADD_CONTEXT_TO_OUTPUT: True
DATAPOINT_LIMIT: -1  # Limit of graphs to load
SEED: 123456
SAVE_PLOTS_LOCALLY: True #Set to False if you dont want to save the qualitative test results and expected vs predicted plots

UPLOAD_TO_WANDB: False

Q_TEST_PATH: 'qualitative_tests'
Q_TEST_FILE: 'qualitative_tests/socnavgym_conf_qualitative_one_static.yaml' 

